/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Example {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Example(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Example obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffi_classJNI.delete_Example(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Example() {
    this(ffi_classJNI.new_Example(), true);
  }

  public void Hello(String str) {
    ffi_classJNI.Example_Hello(swigCPtr, this, str);
  }

  public void Sinc(double x) {
    ffi_classJNI.Example_Sinc(swigCPtr, this, x);
  }

}
