/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ffi_classJNI {
  public final static native long new_Example();
  public final static native void delete_Example(long jarg1);
  public final static native void Example_Hello(long jarg1, Example jarg1_, String jarg2);
  public final static native void Example_Sinc(long jarg1, Example jarg1_, double jarg2);
}
