/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ffi_c {
  public static void hello(String str) {
    ffi_cJNI.hello(str);
  }

  public static double sinc(double x) {
    return ffi_cJNI.sinc(x);
  }

}
